// gvc.web/ClientApp/src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';
import { AboutLinks } from './AboutLinks';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html'
})
export class AboutComponent implements OnInit {
  links: Array<AboutLinks>;
  constructor() {
    this.links = new Array<AboutLinks>();
  }

  ngOnInit() {

    this.links.push({
      url: 'http://bit.ly/2zhCJ4T',
      fontAwesome: 'fab fa-facebook',
      username: '@gvcayetano'
    });

    this.links.push({
      url: 'http://bit.ly/2MB63Ml',
      fontAwesome: 'fab fa-github',
      username: '@gvcayetano'
    });

    this.links.push({
      url: 'http://bit.ly/2PdP9Fz',
      fontAwesome: 'fab fa-instagram',
      username: '@gvcayetano'
    });

    this.links.push({
      url: 'http://bit.ly/2ZpLBQq',
      fontAwesome: 'fab fa-linkedin',
      username: '@gvcayetano'
    });

    this.links.push({
      url: 'http://bit.ly/2HikHUr',
      fontAwesome: 'fab fa-twitter',
      username: '@gvcayetano'
    });
  }

}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5>Hi!</h5>
            <p>You can call me 'Jayjay'. I'm a software engineer based in Manila. </p>
            <p>Here are some links to get to know me better:</p>
        </div>
    </div>
    <div class="row about-links" *ngFor="let link of links">
        <div class="col-md-12">
            <a class="about-links__url" [href]="link.url" target="_blank">
              <i class="{{link.fontAwesome}}"></i> 
              <span class="about-links__username">{{link.username}}</span>
            </a>
        </div>
    </div>
  </div>

// Gvc.ClientApp/src/components/about.jsx
import React, { Component } from "react";
import publicService from "../services/publicService";

class About extends Component {
  state = { socialMediaLinks: [] };
  async componentDidMount() {
    const {
      data: socialMediaLinks
    } = await publicService.getSocialMediaLinks();
    this.setState({ socialMediaLinks });
  }
  render() {
    return (
      <div className="container">
        <div className="row">
          <div className="col">
            <h5>Hi!</h5>
            <p>
              You can call me 'Jayjay'. I'm a software engineer based in Manila.{" "}
            </p>
            <p>Here are some links to get to know me better:</p>
            {this.state.socialMediaLinks.map(sml => (
              <div className="about-links" key={sml.id}>
                <a className="about-links__url" href={sml.url} target="_blank">
                  <i className={sml.fontAwesomeClass}></i>
                  <span className="about-links__username">{sml.username}</span>
                </a>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }
}

export default About;
