// Gvc.ClientApp/pages/about.vue
<template>
  <div>
    <Header />
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h5>Hi!</h5>
          <p>You can call me 'Jayjay'. I'm a software engineer based in Manila. </p>
          <p>Here are some links to get to know me better:</p>
        </div>
      </div>
      <div class="row about-links" v-for="link in socialMediaLinks">
        <div class="col-md-12">
          <a class="about-links__url" :href="link.url" target="_blank">
            <i :class="link.fontAwesomeClass"></i>
            <span class="about-links__username">{{link.username}}</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import Header from '~/components/Header.vue'
  export default {
    data() {
      return {
        socialMediaLinks: []
      }
    },
    components: {
      Header
    },
    head() {
      return {
        title: 'GVC - About'
      }
    },
    methods: {
      async getSocialMediaLinks() {
        this.socialMediaLinks = await this.$axios.$get('/api/about')
      }
    },
    mounted() {
      this.getSocialMediaLinks();
    }
  }
</script>

<style lang="scss" scoped>
    .about-links {
        &__url {
            display: inline-block;
            padding-bottom: 15px;
        }
        i {
            vertical-align: middle;
            font-size: 30px;
            margin-right: 5px;
        }
        &__username {
            vertical-align: middle;
        }
    }
</style>

// Gvc.ClientApp/src/components/about.jsx
import React, { Component } from "react";
import publicService from "../services/publicService";

class About extends Component {
  state = { socialMediaLinks: [] };
  async componentDidMount() {
    const {
      data: socialMediaLinks
    } = await publicService.getSocialMediaLinks();
    this.setState({ socialMediaLinks });
  }
  render() {
    return (
      <div className="container">
        <div className="row">
          <div className="col">
            <h5>Hi!</h5>
            <p>
              You can call me 'Jayjay'. I'm a software engineer based in Manila.{" "}
            </p>
            <p>Here are some links to get to know me better:</p>
            {this.state.socialMediaLinks.map(sml => (
              <div className="about-links" key={sml.id}>
                <a className="about-links__url" href={sml.url} target="_blank">
                  <i className={sml.fontAwesomeClass}></i>
                  <span className="about-links__username">{sml.username}</span>
                </a>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }
}

export default About;
